version: "3.8"

services:
  client:
    container_name: client
    restart: always
    build:
      context: ./chat-client
    env_file:
      - ./chat-client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    container_name: server
    restart: always
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - "5000:5000"
volumes: 
  chat-client:
    name: chat-client
  server:
    name: server
 