version: "3.3"

services:
  client:
    container_name: client
    restart: always
    build:
      context: ./chat-client
    env_file:
      - ./chat-client/.env
    ports:
      - "3000:3000"
  server:
    container_name: server
    restart: always
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
